<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "aw_weather"
 *
 * Auto generated by Extension Builder 2014-01-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Weather',
	'description' => 'fe weather widget based om openweathermap api ',
	'category' => 'fe',
	'author' => 'alexandros',
	'author_email' => 'websurfer992@gmail.com',
	'author_company' => 'alex-web.gr',
	'shy' => '1',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.1.0-6.1.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>