<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "aw_weather"
 *
 * Auto generated by Extension Builder 2014-01-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Weather',
	'description' => 'adds a weather widget in the front-end by using the openweathermap api ',
	'category' => 'plugin',
	'author' => 'Alexandros',
	'author_email' => 'websurfer992@gmail.com',
	'author_company' => 'alex-web.gr',
	'shy' => '1',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
            'typo3' => '6.1.2-6.1.4',
            'extbase' => '6.0',
            'fluid' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>